' ---------------------------------------------------------------------------
' GIS_macro_for_bathymetry.vbs 
'   (generated by ArcGIS/ModelBuilder)
' ---------------------------------------------------------------------------

' Create the Geoprocessor object
set gp = WScript.CreateObject("esriGeoprocessing.GPDispatch.1")

' Check out any necessary licenses
gp.CheckOutExtension "3D"
gp.CheckOutExtension "spatial"

' Load required toolboxes...
gp.AddToolbox "C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx"
gp.AddToolbox "C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx"
gp.AddToolbox "C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/3D Analyst Tools.tbx"


' Local variables...
echosounder_Layer = "echosounder_Layer"
shore_line_Layer = "shore_line_Layer"
echosounder_data_dbf = "D:\Bathymetry\data_LfU\echosounder_data.dbf"
raw_data_shore_line = "raw_data_shore_line"
Spatial_Reference = "PROJCS['DHDN_3_Degree_Gauss_Zone_4',GEOGCS['GCS_Deutsches_Hauptdreiecksnetz',DATUM['D_Deutsches_Hauptdreiecksnetz',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Gauss_Kruger'],PARAMETER['False_Easting',4500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',12.0],PARAMETER['Scale_Factor',1.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];IsHighPrecision"
Spatial_Reference__2_ = "PROJCS['DHDN_3_Degree_Gauss_Zone_4',GEOGCS['GCS_Deutsches_Hauptdreiecksnetz',DATUM['D_Deutsches_Hauptdreiecksnetz',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Gauss_Kruger'],PARAMETER['False_Easting',4500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',12.0],PARAMETER['Scale_Factor',1.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];IsHighPrecision"
surface_shp = "D:\Bathymetry\data_LfU\surface.shp"
bathymetry_tin = "D:\Bathymetry\data_LfU\bathymetry"
surface = "D:\Bathymetry\data_LfU\surface"
Volume_under_0_txt = "D:\Bathymetry\data_LfU\Volume_under_0.txt"

' Process: Make XY Event Layer...
gp.MakeXYEventLayer_management echosounder_data_dbf, "N1", "N2", echosounder_Layer, Spatial_Reference__2_

' Process: Make XY Event Layer (2)...
gp.MakeXYEventLayer_management raw_data_shore_line, "N1", "N2", shore_line_Layer, Spatial_Reference

' Process: Merge...
gp.Merge_management "echosounder_Layer;shore_line_Layer", surface_shp, "N1 'N1' true true false 11 Double 2 10 ,First,#,echosounder_Layer,N1,-1,-1,shore_line_Layer,N1,-1,-1;N2 'N2' true true false 11 Double 2 10 ,First,#,echosounder_Layer,N2,-1,-1,shore_line_Layer,N2,-1,-1;N3 'N3' true true false 11 Double 2 10 ,First,#,echosounder_Layer,N3,-1,-1,shore_line_Layer,N3,-1,-1"

' Process: IDW...
gp.Idw_sa surface_shp, "N3", surface, "22,23316", "2", "VARIABLE 12", ""

' Process: Raster to TIN...
gp.RasterTin_3d surface, bathymetry_tin, "8,37200012207031", "1500000", "1"

' Process: Surface Volume...
gp.SurfaceVolume_3d bathymetry_tin, Voulme_unter_0_txt, "BELOW", "533,5", "1"

Enter file contents here
